version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      args: 
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    restart: always
    networks:
        - mynetwork

  wordpress:                         
    build:
      context: ./requirements/wordpress/
      args: 
        - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
        - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
        - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
        - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
        - WORDPRESS_ROOT_USER=$WORDPRESS_ROOT_USER
        - WORDPRESS_ROOT_PASSWORD=$WORDPRESS_ROOT_PASSWORD
        - WORDPRESS_USER=$WORDPRESS_USER
        - WORDPRESS_PASSWORD=$WORDPRESS_PASSWORD
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_nginx:/var/www/html/wordpress
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - mynetwork
    restart: always
 
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_nginx:/var/www/html/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    networks:
      - mynetwork
  
  website:
    build: ./requirements/bonus/website/
    image: website
    container_name: website
    ports:
      - 1337:1337
    restart: always
    networks:
      - mynetwork

  # adminer:
  #   build: ./requirements/bonus/adminer/
  #   image: adminer
  #   container_name: adminer
  #   env_file: .env
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - mynetwork

  # ftp:
  #   build:
  #     context: ./requirements/bonus/ftp/
  #     args: 
  #       - FTP_USER_NAME=$FTP_USER_NAME
  #       - FTP_USER_PASS=$FTP_USER_PASS
  #       - FTP_USER_HOME=$FTP_USER_HOME
  #   image: ftp
  #   container_name: ftp
  #   env_file: .env
  #   restart: always
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "21:21"
  #     - "40000-40009:40000-40009"
  #   volumes:
  #     - wordpress_nginx:/home/mmounchi/ftp
  #   networks:
  #     - mynetwork 

  # cadvisor:
  #   build: ./requirements/bonus/cadvisor/
  #   image: cadvisor
  #   container_name: cadvisor
  #   env_file: .env
  #   restart: always    
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - mynetwork

  # redis:
  #   build: ./requirements/bonus/redis/
  #   image: redis
  #   container_name: redis
  #   env_file: .env
  #   restart: always
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - mynetwork

volumes:
  mariadb_data:
    # name: mariadb_data
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/mmounchi/data/mariadb_data
  wordpress_nginx:
    # name: wordpress_nginx
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/mmounchi/data/wordpress_nginx

networks:
  mynetwork:
    # name: mynetwork  
    driver: bridge