---
- name: MyAnsible
  hosts: mycloud
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: /home/misaki/Desktop/misa.cer

  tasks:
    - name: Update package lists
      command: apt update

    - name: Install Apache web server
      apt:
        name: apache2
        state: present
        
    - name: Install net-tools
      command: apt install net-tools

    - name: Start Apache web server
      service:
        name: apache2
        state: started

    - name: Copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/

    - name: Change host name
      copy:
        src: ./hosts.sh
        dest: /hosts.sh

    - name: Change host name2
      command: sh /hosts.sh

    - name: can i use echo?
      ansible.builtin.lineinfile:
        path: /hosts.sh
        line: echo "hi"