---
- name: Test Docker
  hosts: mycloud
  become: true
  become_method: sudo
  # become_user: root
  vars:
    ansible_ssh_private_key_file: /home/misaki/Desktop/misa.cer

  tasks:
  - name: Rebooting the cloud server/bare metal box
    reboot:
      test_command: uptime

# sudo ansible-playbook reboot_me.yaml