---
- name: MyAnsible
  hosts: mycloud
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: /home/misaki/Desktop/misa.cer

  tasks:
    - name: Update package lists
      command: apt update
    - name: Check for the latest sl version
      apt:
        name: sl
        state: latest